#!/usr/bin/env python3
"""Write paper/tab-regrade.tex: each arm as originally graded and after each correction.

Splits the move from the stored verdict to the reported one by cause: flips on the four
problems whose answer key accepts more than one answer, and flips on every other problem,
which are the ones re-execution as a subprocess fixes (Appendix on the evaluator).
"""
import os
import json

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
VERDICTS = os.path.join(ROOT, "runs", "patched_verdicts.json")
OUT = os.path.join(ROOT, "paper", "tab-regrade.tex")

# The four LCB-100 problems whose stored key is not the only accepted answer.
KEYS = {"abc396_e", "arc190_a", "arc195_c", "abc385_f"}

PINNED = [
    ("Claude Fable 5",      "fable5-128k-reasoning-on-5pass",     ["fable5_single_p%d"], None),
    ("GPT-5.6-Terra",       "firstparty-128k-reasoning-on-5pass", ["terra_single_p%d"], ["terra_multiagent_p%d"]),
    ("GPT-5.6-Luna",        "firstparty-128k-reasoning-on-5pass", ["luna_single_p%d"], ["luna_multiagent_p%d"]),
    ("Qwen3.8-27B",         "firstparty-128k-reasoning-on-5pass", ["q38_single_p%d.cap128k"], ["q38_multiagent_p%d"]),
    ("Qwen3.8-Flash-Next",  "q38-fn-5pass",                       ["q38_fn_single_p%d"], ["q38_fn_multiagent_p%d"]),
    ("DeepSeek-V4.1-Flash", "ds-v41-f-5pass",                     ["ds_v41_f_single_p%d"], ["ds_v41_f_multiagent_p%d"]),
]

OPENROUTER = [
    ("Opus-5",      "opus_single",  "opus_multiagent"),
    ("Kimi-K3",     "kimi_single",  "kimi_multiagent"),
    ("MiniMax-M3",  "mm3_single",   "mm3_multiagent"),
    ("Qwen3.6-35B", "q35_single",   "q35_multiagent"),
]
OR_RUN = "128k-reasoning-on-1pass"


def stored_records(run, arm):
    path = os.path.join(ROOT, "runs", run, "results", f"{arm}.json")
    return {r["question_id"]: r for r in json.load(open(path))["lcb"]["records"]}


def arm_stats(verdicts, run, arm):
    """(stored pass@1, delta from the key fix, delta from the harness fix, reported)."""
    rec = stored_records(run, arm)
    new = verdicts[run][arm]["verdicts"]
    graded = [q for q, r in rec.items() if r.get("status") != "infra"]
    n = len(graded)
    old_n = sum(bool(rec[q].get("passed")) for q in graded)
    d_key = d_harness = 0
    for q in graded:
        move = bool(new[q]) - bool(rec[q].get("passed"))
        if q in KEYS:
            d_key += move
        else:
            d_harness += move
    return (100.0 * old_n / n, 100.0 * d_key / n, 100.0 * d_harness / n,
            verdicts[run][arm]["new_pass@1"])


def mean_stats(verdicts, run, patterns):
    rows = [arm_stats(verdicts, run, p % i) for p in patterns for i in range(1, 6)]
    return tuple(sum(c) / len(rows) for c in zip(*rows))


def fmt(model, s, m):
    def cell(v, signed=False):
        if v is None:
            return "---"
        return f"${v:+.1f}$" if signed else f"{v:.1f}"

    def group(x):
        if x is None:
            return " & ".join(["---"] * 4)
        return " & ".join([cell(x[0]), cell(x[2], True), cell(x[1], True),
                           f"\\textbf{{{x[3]:.1f}}}"])
    return f"{model} & {group(s)} & {group(m)} \\\\"


def main():
    v = json.load(open(VERDICTS))
    lines = []
    for model, run, single, multi in PINNED:
        s = mean_stats(v, run, single)
        m = mean_stats(v, run, multi) if multi else None
        lines.append(fmt(model, s, m))
    or_lines = []
    for model, single, multi in OPENROUTER:
        or_lines.append(fmt(model, arm_stats(v, OR_RUN, single),
                            arm_stats(v, OR_RUN, multi)))

    body = "\n".join(lines)
    or_body = "\n".join(or_lines)
    tex = r"""%% Generated by paper_plot_script/make_regrade_table.py -- do not edit.
\begin{table}[htbp]
\centering
\caption{\textbf{Every reported arm as the stock evaluator graded it, and after each
correction} (Appendix~\ref{app:evaluator}). \textbf{As graded} is LiveCodeBench's own
verdict on the stored generations. \textbf{Harness} is the move contributed by running
each submission as a subprocess, which is what repairs the \texttt{sys.stdin} mock and
\texttt{sys.stdout.buffer}; \textbf{keys} is the move contributed by judging the four
problems that accept more than one answer by the contest's rule. \textbf{Reported} is the
number used everywhere else in this paper. Upper block: five-pass means at a 128k cap,
reasoning on (Table~\ref{tab:main}). Lower block: the 128k reasoning-on, one-pass
OpenRouter arms (Table~\ref{tab:openrouter}); Qwen3.5-9B is unusable in this condition and
is omitted. Across the 48 arm-passes of the two remaining OpenRouter conditions the harness
correction moves six by one point and the key correction moves each arm by 0 to 3 points.}
\label{tab:regrade}
\small
\setlength{\tabcolsep}{4pt}
\begin{tabular}{@{}lcccc@{\hspace{1.2em}}cccc@{}}
\toprule
& \multicolumn{4}{c}{\textbf{Single call}} & \multicolumn{4}{c}{\textbf{With manager}} \\
\cmidrule(r){2-5}\cmidrule(l){6-9}
\textbf{Model} & \textbf{\shortstack{As\\graded}} & \textbf{\shortstack{$\Delta$\\harness}}
& \textbf{\shortstack{$\Delta$\\keys}} & \textbf{\shortstack{Re-\\ported}}
& \textbf{\shortstack{As\\graded}} & \textbf{\shortstack{$\Delta$\\harness}}
& \textbf{\shortstack{$\Delta$\\keys}} & \textbf{\shortstack{Re-\\ported}} \\
\midrule
\multicolumn{9}{@{}l}{\emph{Pinned backends, five passes}} \\
@PINNEDROWS@
\midrule
\multicolumn{9}{@{}l}{\emph{OpenRouter-served, one pass}} \\
@ORROWS@
\bottomrule
\end{tabular}
\end{table}
""".replace("@PINNEDROWS@", body).replace("@ORROWS@", or_body)
    with open(OUT, "w") as f:
        f.write(tex)
    print("wrote", OUT)
    print(tex)


if __name__ == "__main__":
    main()
