#!/usr/bin/env python3
"""Write paper/tab-qwen-caps.tex and paper/tab-emitted.tex.

Both were typed by hand and both quote pass@1, so both went stale the moment the grading
changed. They are computed here from the same *.patched.json files the charts read, so all
three tables and every figure now come off one grading.

  tab:qwen-caps  Qwen3.8-27B's single arm at each cap: score, how often the generation hit
                 the cap (finish_reason=length), how often nothing gradable came back.
  tab:emitted    Each pinned-backend single arm re-scored over only the problem-passes
                 where it emitted code -- the ceiling an emit-rate fix could reach.

    uv run --with numpy --with scipy python paper_plot_script/make_arm_tables.py
"""
import os
import json
import statistics as st

from plot_16k_reason_off_5_pass import pass_ci
from plot_4new_5pass_reason_on import compute as pinned_stats, p_tex

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PAPER = os.path.join(ROOT, "paper")
R4 = os.path.join(ROOT, "runs/firstparty-128k-reasoning-on-5pass/results")
RF = os.path.join(ROOT, "runs/fable5-128k-reasoning-on-5pass/results")
PASSES = 5


def load(pattern):
    """-> list of per-pass record lists."""
    return [json.load(open(pattern % p))["lcb"]["records"] for p in range(1, PASSES + 1)]


def score(passes):
    return [100.0 * sum(bool(r["passed"]) for r in recs) / len(recs) for recs in passes]


def emitted(recs):
    return [r for r in recs if (r.get("code") or "").strip()]


def qwen_caps():
    # "Cut off by the cap" means a different test per row. The 250k row is the generation as
    # it ran, so its cap hits are finish_reason=length against the 250k ceiling. The 128k row
    # is a replay of those same generations truncated at 128k, and capmatch_q38.py does not
    # rewrite finish_reason -- what was cut there is whatever ran past 128,000 output tokens.
    rows = []
    for label, pat, cut_hit in (
            (r"128k (cap-matched, App.~\ref{app:protocol})",
             f"{R4}/q38_single_p%d.cap128k.patched.json",
             lambda r: (r.get("completion_tokens") or 0) >= 128_000),
            ("250k (as generated)", f"{R4}/q38_single_p%d.patched.json",
             lambda r: r.get("finish_reason") == "length")):
        passes = load(pat)
        flat = [r for recs in passes for r in recs]
        n = len(flat)
        lo, hi = pass_ci(score(passes))
        mean, half = (lo + hi) / 2, (hi - lo) / 2
        cut = sum(1 for r in flat if cut_hit(r))
        nocode = n - len(emitted(flat))
        rows.append((label, rf"${mean:.1f} \pm {half:.1f}$",
                     rf"{cut} / {n} \ ({100.0 * cut / n:.1f}\,\%)",
                     rf"{nocode} / {n} \ ({100.0 * nocode / n:.1f}\,\%)"))
    return rows


def emitted_table():
    arms = [("GPT-5.6-Terra", f"{R4}/terra_single_p%d.patched.json"),
            ("GPT-5.6-Luna", f"{R4}/luna_single_p%d.patched.json"),
            ("Qwen3.8-27B", f"{R4}/q38_single_p%d.cap128k.patched.json"),
            ("Claude Fable 5", f"{RF}/fable5_single_p%d.patched.json")]
    rows = []
    for label, pat in arms:
        passes = load(pat)
        flat = [r for recs in passes for r in recs]
        n = len(flat)
        as_scored = st.mean(score(passes))
        emit = emitted(flat)
        restricted = 100.0 * sum(bool(r["passed"]) for r in emit) / len(emit)
        d = restricted - as_scored
        tail = "" if len(emit) == n else rf" (${'+' if d >= 0 else '-'}{abs(d):.1f}$)"
        rows.append((label, f"{as_scored:.1f}", f"{len(emit)}/{n}", f"{restricted:.1f}{tail}"))
    return rows


def agreement_table():
    """Problem-passes won by exactly one arm. Read off the same compute() that makes
    Table~\\ref{tab:main} and the bars, so the two cannot disagree about a run."""
    return [(s["label"], str(s["mgr_only"]), str(s["sgl_only"]), str(s["n_pp"]),
             p_tex(s["mcnemar_p"]))
            for s in pinned_stats() if s["has_mgr"]]


def write(path, caption, label, header, rows, colspec="@{}lccc@{}"):
    out = [r"\begin{table}[htbp]", r"\centering", r"\caption{" + caption + "}",
           rf"\label{{{label}}}", r"\small", rf"\begin{{tabular}}{{{colspec}}}", r"\toprule",
           header, r"\midrule"]
    width = max(len(r[0]) for r in rows)
    for r in rows:
        out.append(f"{r[0]:<{width}} & " + " & ".join(r[1:]) + r" \\")
    out += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    full = os.path.join(PAPER, path)
    with open(full, "w") as f:
        f.write("% Generated by paper_plot_script/make_arm_tables.py -- do not edit.\n")
        f.write("\n".join(out) + "\n")
    return full


def main():
    caps = qwen_caps()
    write("tab-qwen-caps.tex",
          r"\textbf{Qwen3.8-27B's single arm read at both caps.} Cap-matched to 128k, and as "
          r"generated at 250k. Scores are from the patched grader (Section~\ref{sec:setup}); "
          r"$\pm$ is a 95\% $t$ interval across the five passes.",
          "tab:qwen-caps",
          r"\textbf{Qwen3.8-27B single} & \textbf{pass@1} & \textbf{Cut off by the cap} &"
          "\n" r"\textbf{No code at all} \\", caps)
    emit = emitted_table()
    write("tab-emitted.tex",
          r"\textbf{Each single arm re-scored} over only the problem-passes where it emitted "
          r"code. Scores are from the patched grader (Section~\ref{sec:setup}).",
          "tab:emitted",
          r"\textbf{Model (single arm)} & \textbf{As scored} & \textbf{Emitted code} &"
          "\n" r"\textbf{Restricted to those} \\", emit)
    agree = agreement_table()
    write("tab-agreement.tex",
          r"\textbf{Problem-passes won by one arm alone.} Of the 500 problem-passes per "
          r"model (100 problems $\times$ 5 passes), the number the manager arm solved and "
          r"the single call did not, against the number the single call solved and the "
          r"manager did not. The gains are not compensating wins and losses. The test is "
          r"exact McNemar on those discordant pairs (Section~\ref{sec:setup}).",
          "tab:agreement",
          r"\textbf{Model} & \textbf{Manager only} & \textbf{Single call only} &"
          "\n" r"\textbf{Problem-passes} & \textbf{Exact McNemar $p$} \\", agree,
          colspec="@{}lcccc@{}")
    for r in caps + emit + agree:
        print(" | ".join(r))
    print(f"\nWrote {PAPER}/tab-qwen-caps.tex, tab-emitted.tex and tab-agreement.tex")


if __name__ == "__main__":
    main()
